project:
  type: website
  output-dir: ./docs  # rendered html pages will be stored here
  resources:
    - interactive/**

website:
  title: "Sungyeon Hong"
  google-analytics: "G-CPXYZFK8GC"
  navbar:
    left:
      - text: Research
        menu:
          - text: Overview
            href: research.qmd
          - text: Order, disorder and in-between
            href: research/hyperuniformity.qmd
          - text: Information dynamics
            href: research/information-dynamics.qmd
          - text: Embodied complexity
            href: research/embodied-complexity.qmd
      - text: Education
        href: education.qmd
      - text: Engagements
        href: engagements.qmd
      - text: Resources
        href: resources.qmd
      - text: FAQ
        href: faq.qmd
#      - text: Contact
#        href: contact.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
